version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VISUAL_CROSSING_API_KEY=${VISUAL_CROSSING_API_KEY}
      - EBAY_APP_ID=${EBAY_APP_ID}
      - FAL_KEY=${FAL_KEY}
    networks:
      - mynet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_VISUAL_CROSSING_API_KEY=${REACT_APP_VISUAL_CROSSING_API_KEY}
    networks:
      - mynet

networks:
  mynet:
